### ISSUE TITLE
MonadFail instance

### ISSUE THREAD

**Issue by zilinc** [emilaxelsson/haskell-exp-parser#2]
In recent versions of GHC, due to the MonadFail proposal (https://gitlab.haskell.org/ghc/ghc/-/wikis/proposal/monad-fail), `Either e a` doesn't have `fail` defined. `Left` can be used instead of `fail`.

**Comment by emilaxelsson** [comment]
Thanks for the report!

**Comment by zilinc** [comment]
Many thanks.
