### ISSUE TITLE
compatibility with template-haskell >= 2.16

### ISSUE THREAD

**Issue by zilinc** [emilaxelsson/haskell-exp-parser#3]
On https://github.com/emilaxelsson/haskell-exp-parser/blob/master/src/Language/Haskell/ParseExp.hs#L92, the `TupE` constructor now takes `[Maybe Exp]` rather than `[Exp]`. The change was introduced in template-haskell-2.16.0.0.

**Comment by emilaxelsson** [comment]
Thanks for the report!
